#!/usr/bin/env python3
"""Generate LFO rate7 → DDS phase increment LUT."""

from __future__ import annotations

import argparse
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CLK_HZ_DEFAULT = 1_000_000
F_MIN = 0.1
F_MAX = 30.0


def rate_to_hz(rate7: int) -> float:
    if rate7 <= 0:
        return F_MIN
    t = rate7 / 127.0
    return F_MIN * (F_MAX / F_MIN) ** t


def emit_lut(clk_hz: int, entries: list[tuple[int, int]]) -> str:
    lines = ["// Auto-generated by tools/gen_lfo_rate_lut.py — do not edit."]
    lines.append("module lfo_rate_lut(")
    lines.append("    input  wire [6:0] rate7,")
    lines.append("    output reg  [31:0] adder")
    lines.append(");")
    lines.append("    always @(*) begin")
    lines.append("        case (rate7)")
    for rate, add in entries:
        lines.append(f"            7'd{rate}: adder = 32'd{add};")
    lines.append("            default: adder = 32'd0;")
    lines.append("        endcase")
    lines.append("    end")
    lines.append("endmodule")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--clk-hz", type=int, default=CLK_HZ_DEFAULT)
    parser.add_argument("--out", type=Path, default=ROOT / "lfo/lfo_rate_lut.v")
    args = parser.parse_args()

    entries: list[tuple[int, int]] = []
    for rate in range(128):
        f_hz = rate_to_hz(rate)
        adder = int(round((2**32) * f_hz / args.clk_hz))
        adder = min(adder, (1 << 32) - 1)
        entries.append((rate, adder))

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(emit_lut(args.clk_hz, entries), encoding="utf-8")
    print(f"Wrote {args.out}")
    print(f"  rate=0   f={rate_to_hz(0):.3f} Hz  adder={entries[0][1]}")
    print(f"  rate=64  f={rate_to_hz(64):.3f} Hz  adder={entries[64][1]}")
    print(f"  rate=127 f={rate_to_hz(127):.3f} Hz  adder={entries[127][1]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
