#!/usr/bin/env python3
"""Generate SVF cutoff/resonance LUT Verilog for mono_synth."""

from __future__ import annotations

import argparse
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCALE = 131072.0
FS_DEFAULT = 1_000_000
FC_MIN_DEFAULT = 10.0
FC_MAX_DEFAULT = 20_000.0
Q_MIN = 0.5
Q_MAX = 16.0


def f_coeff_for_fc(fc_hz: float, fs_hz: float) -> int:
    fv = 2.0 * math.sin(math.pi * fc_hz / fs_hz)
    return min(int(round(fv * SCALE)), 131071)


def fc_hz_from_f(f: int, fs_hz: float) -> float:
    fv = f / SCALE
    return fs_hz * math.asin(min(fv / 2.0, 1.0)) / math.pi


def q_coeff(q: float) -> int:
    qv = 1.0 / max(q, Q_MIN)
    return min(int(round(qv * SCALE)), 131071)


def emit_case_lut(
    name: str,
    index_bits: int,
    port_name: str,
    out_name: str,
    entries: list[tuple[int, int]],
) -> str:
    lines = ["// Auto-generated by tools/gen_svf_cc_lut.py — do not edit."]
    lines.append(f"module {name}(")
    lines.append(f"    input  wire [{index_bits - 1}:0] {port_name},")
    lines.append(f"    output reg  [17:0] {out_name}")
    lines.append(");")
    lines.append("    always @(*) begin")
    lines.append(f"        case ({port_name})")
    for idx, val in entries:
        lines.append(f"            {index_bits}'d{idx}: {out_name} = 18'd{val};")
    lines.append(f"            default: {out_name} = 18'd0;")
    lines.append("        endcase")
    lines.append("    end")
    lines.append("endmodule")
    lines.append("")
    return "\n".join(lines)


def emit_q_lut(entries: list[tuple[int, int]]) -> str:
    return emit_case_lut("svf_cc_to_q", 7, "cc", "q", entries)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--fs", type=float, default=FS_DEFAULT, help="SVF tick rate (CLK_Hz)")
    parser.add_argument("--fc-min", type=float, default=FC_MIN_DEFAULT)
    parser.add_argument("--fc-max", type=float, default=FC_MAX_DEFAULT)
    parser.add_argument("--bits", type=int, default=14, choices=(7, 14))
    parser.add_argument("--out-dir", type=Path, default=ROOT / "synths/mono_synth")
    args = parser.parse_args()

    args.out_dir.mkdir(parents=True, exist_ok=True)

    n = (1 << args.bits) - 1
    ratio = args.fc_max / args.fc_min
    f_entries: list[tuple[int, int]] = []
    for idx in range(1 << args.bits):
        t = idx / n
        fc = args.fc_min * (ratio**t)
        f_entries.append((idx, f_coeff_for_fc(fc, args.fs)))

    if args.bits == 14:
        f_path = args.out_dir / "svf_cutoff14_to_f.v"
        f_path.write_text(
            emit_case_lut("svf_cutoff14_to_f", 14, "idx", "f", f_entries),
            encoding="utf-8",
        )
        print(f"Wrote {f_path} ({len(f_entries)} entries)")
    else:
        f_path = args.out_dir / "svf_cc_to_f.v"
        f_entries_7 = f_entries[:128]
        f_path.write_text(
            emit_case_lut("svf_cc_to_f", 7, "cc", "f", f_entries_7),
            encoding="utf-8",
        )
        print(f"Wrote {f_path} (128 entries)")

    q_entries = [
        (cc, q_coeff(Q_MAX * ((Q_MIN / Q_MAX) ** (cc / 127.0)))) for cc in range(128)
    ]
    q_path = args.out_dir / "svf_cc_to_q.v"
    q_path.write_text(emit_q_lut(q_entries), encoding="utf-8")
    print(f"Wrote {q_path}")

    f_min = f_entries[0][1]
    f_max = f_entries[-1][1]
    print(f"  fs={args.fs:.0f} Hz  fc={args.fc_min:.0f}..{args.fc_max:.0f} Hz")
    print(f"  idx=0    Fc≈{fc_hz_from_f(f_min, args.fs):.1f} Hz  f={f_min}")
    print(f"  idx={n}  Fc≈{fc_hz_from_f(f_max, args.fs):.1f} Hz  f={f_max}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
