#!/usr/bin/env python3
"""Generate vst_bridge APVTS helpers from mono_synth.params.yaml."""

from __future__ import annotations

import argparse
import textwrap
from pathlib import Path

try:
    import yaml
except ImportError as exc:  # pragma: no cover
    raise SystemExit("PyYAML required: pip install pyyaml") from exc

ROOT = Path(__file__).resolve().parents[1]


def load_params(path: Path) -> tuple[int, list[dict]]:
    with path.open(encoding="utf-8") as fh:
        data = yaml.safe_load(fh)
    channel = int(data.get("midi_channel", 1))
    params = data["params"]
    return channel, params


def cpp_string(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def gen_header(channel: int, params: list[dict], yaml_path: Path) -> str:
    lines = [
        "// Generated by tools/gen_vst_apvts.py — do not edit.",
        f"// Source: {yaml_path.as_posix()}",
        "#pragma once",
        "",
        "#include <JuceHeader.h>",
        "",
        "namespace synthparams {",
        "",
        f"inline constexpr int kMidiChannel = {channel};",
        "",
        "struct ParamIds {",
    ]
    for param in params:
        lines.append(f'    static constexpr const char* {param["id"]} = "{param["id"]}";')
    lines.extend(
        [
            "};",
            "",
            "inline constexpr const char* kParamIds[] = {",
        ]
    )
    for param in params:
        lines.append(f"    ParamIds::{param['id']},")
    lines.extend(
        [
            "};",
            "",
            "juce::AudioProcessorValueTreeState::ParameterLayout createParameterLayout();",
            "void sendParamAsMidi(juce::AudioProcessorValueTreeState& apvts,",
            "                       const juce::String& paramId,",
            "                       float normalizedValue,",
            "                       const std::function<void(const std::vector<uint8_t>&)>& sendBytes);",
            "",
            "}  // namespace synthparams",
            "",
        ]
    )
    return "\n".join(lines)


def gen_cpp(channel: int, params: list[dict], yaml_path: Path) -> str:
    ch0 = channel - 1
    status_cc = f"0xB0 + {ch0}"

    layout_lines = ["juce::AudioProcessorValueTreeState::ParameterLayout createParameterLayout() {", "    std::vector<std::unique_ptr<juce::RangedAudioParameter>> p;"]

    for param in params:
        pid = param["id"]
        name = param["name"]
        ptype = param["type"]
        if ptype == "cc7":
            default = float(param.get("default", 64)) / 127.0
            layout_lines.append(
                textwrap.dedent(
                    f"""
                p.push_back(std::make_unique<juce::AudioParameterFloat>(
                    juce::ParameterID{{{cpp_string(pid)}, 1}},
                    {cpp_string(name)},
                    juce::NormalisableRange<float>(0.0f, 1.0f),
                    {default:.6f}f));
                """
                ).strip()
            )
        elif ptype == "cc14_log":
            default = float(param.get("default", 8192)) / 16383.0
            layout_lines.append(
                textwrap.dedent(
                    f"""
                p.push_back(std::make_unique<juce::AudioParameterFloat>(
                    juce::ParameterID{{{cpp_string(pid)}, 1}},
                    {cpp_string(name)},
                    juce::NormalisableRange<float>(0.0f, 1.0f),
                    {default:.6f}f));
                """
                ).strip()
            )
        elif ptype == "choice":
            choices = param["choices"]
            default_idx = int(param.get("default", 0))
            choice_args = ", ".join(cpp_string(c) for c in choices)
            layout_lines.append(
                textwrap.dedent(
                    f"""
                p.push_back(std::make_unique<juce::AudioParameterChoice>(
                    juce::ParameterID{{{cpp_string(pid)}, 1}},
                    {cpp_string(name)},
                    juce::StringArray{{{choice_args}}},
                    {default_idx}));
                """
                ).strip()
            )

    layout_lines.extend(["    return {p.begin(), p.end()};", "}"])

    send_cases = [
        "void sendParamAsMidi(juce::AudioProcessorValueTreeState& apvts,",
        "                       const juce::String& paramId,",
        "                       float normalizedValue,",
        "                       const std::function<void(const std::vector<uint8_t>&)>& sendBytes) {",
        f"    const uint8_t status = static_cast<uint8_t>({status_cc});",
        "    auto* parameter = apvts.getParameter(paramId);",
        "    const float raw = parameter != nullptr ? parameter->getValue() : normalizedValue;",
        "    const float clamped = juce::jlimit(0.0f, 1.0f, raw);",
    ]

    for param in params:
        pid = param["id"]
        ptype = param["type"]
        send_cases.append(f'    if (paramId == ParamIds::{pid}) {{')
        if ptype == "cc7":
            cc = int(param["cc"])
            send_cases.extend(
                [
                    f"        const int value = juce::roundToInt(clamped * 127.0f);",
                    f"        sendBytes({{status, {cc}, static_cast<uint8_t>(value)}});",
                    "        return;",
                    "    }",
                ]
            )
        elif ptype == "cc14_log":
            send_cases.extend(
                [
                    "        const int value14 = juce::roundToInt(clamped * 16383.0f);",
                    f"        const uint8_t msb = static_cast<uint8_t>((value14 >> 7) & 0x7F);",
                    f"        const uint8_t lsb = static_cast<uint8_t>(value14 & 0x7F);",
                    f"        sendBytes({{status, {int(param['cc_lsb'])}, msb}});",
                    f"        sendBytes({{status, {int(param['cc_msb'])}, lsb}});",
                    "        return;",
                    "    }",
                ]
            )
        elif ptype == "choice":
            cc = int(param["cc"])
            n = len(param["choices"])
            midi_values = [int(v) for v in param.get("midi_values", [])]
            if midi_values:
                values = ", ".join(str(v) for v in midi_values)
                send_cases.extend(
                    [
                        f"        static constexpr uint8_t values[] = {{{values}}};",
                        f"        const int idx = juce::jlimit(0, {n - 1}, juce::roundToInt(clamped * {max(n - 1, 0)}.0f));",
                        "        sendBytes({status, "
                        f"{cc}, values[static_cast<std::size_t>(idx)]"
                        "});",
                        "        return;",
                        "    }",
                    ]
                )
                continue
            denominator = max(n - 1, 1)
            send_cases.extend(
                [
                    f"        const int idx = juce::roundToInt(clamped * {max(n - 1, 0)}.0f);",
                    f"        const int ccValue = idx * 127 / {denominator};",
                    f"        sendBytes({{status, {cc}, static_cast<uint8_t>(ccValue)}});",
                    "        return;",
                    "    }",
                ]
            )

    send_cases.extend(["}", ""])

    body = [
        "// Generated by tools/gen_vst_apvts.py — do not edit.",
        f"// Source: {yaml_path.as_posix()}",
        '#include "SynthParams.h"',
        "",
        "#include <vector>",
        "",
        "namespace synthparams {",
        "",
        *layout_lines,
        "",
        *send_cases,
        "}  // namespace synthparams",
        "",
    ]
    return "\n".join(body)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--yaml",
        type=Path,
        default=ROOT / "synths/mono_synth/mono_synth.params.yaml",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=ROOT / "vst_bridge/generated",
    )
    args = parser.parse_args()

    channel, params = load_params(args.yaml)
    args.out_dir.mkdir(parents=True, exist_ok=True)

    header = args.out_dir / "SynthParams.h"
    cpp = args.out_dir / "SynthParams.cpp"
    header.write_text(gen_header(channel, params, args.yaml), encoding="utf-8")
    cpp.write_text(gen_cpp(channel, params, args.yaml), encoding="utf-8")
    print(f"Wrote {header}")
    print(f"Wrote {cpp}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
