#!/usr/bin/env python3
"""Generate note → fcut14 LUT for SVF key follow (1:1 with note fundamental)."""

from __future__ import annotations

import argparse
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
FS_DEFAULT = 1_000_000
FC_MIN_DEFAULT = 10.0
FC_MAX_DEFAULT = 20_000.0


def midi_note_hz(note: int) -> float:
    return 440.0 * (2.0 ** ((note - 69) / 12.0))


def fc_hz_to_fcut14(fc_hz: float, fc_min: float, fc_max: float, bits: int = 14) -> int:
    fc_hz = max(fc_min, min(fc_max, fc_hz))
    n = (1 << bits) - 1
    ratio = fc_max / fc_min
    t = math.log(fc_hz / fc_min) / math.log(ratio)
    return int(round(t * n))


def emit_note_fcut_lut(entries: list[tuple[int, int]]) -> str:
    lines = ["// Auto-generated by tools/gen_note_fcut_lut.py — do not edit."]
    lines.append("module note_fcut_lut(")
    lines.append("    input  wire [6:0] note,")
    lines.append("    output reg  [13:0] idx")
    lines.append(");")
    lines.append("    always @(*) begin")
    lines.append("        case (note)")
    for note, idx in entries:
        lines.append(f"            7'd{note}: idx = 14'd{idx};")
    lines.append("            default: idx = 14'd0;")
    lines.append("        endcase")
    lines.append("    end")
    lines.append("endmodule")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--fc-min", type=float, default=FC_MIN_DEFAULT)
    parser.add_argument("--fc-max", type=float, default=FC_MAX_DEFAULT)
    parser.add_argument("--out", type=Path, default=ROOT / "svf/note_fcut_lut.v")
    args = parser.parse_args()

    entries: list[tuple[int, int]] = []
    for note in range(128):
        hz = midi_note_hz(note)
        entries.append((note, fc_hz_to_fcut14(hz, args.fc_min, args.fc_max)))

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(emit_note_fcut_lut(entries), encoding="utf-8")
    print(f"Wrote {args.out} (128 notes)")
    print(f"  note 60 (C4) idx={entries[60][1]}  hz={midi_note_hz(60):.1f}")
    print(f"  note 69 (A4) idx={entries[69][1]}  hz={midi_note_hz(69):.1f}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
